services:
  db:
    container_name: predev-postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready -U root -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
